config/routes.rb
Rails.application.routes.draw do
  resources :events

  root 'home#index'

  get 'add_arrival' => 'events#add_arrival'
  get 'add_departure' => 'events#add_departure'
  get 'data.csv' => 'home#csv', as: 'data_csv'
  get 'delete_all_events' => 'events#delete_all', as: 'delete_all'

end

app/models/Trip.rb
class Trip
  attr_reader :departure, :arrival

  def initialize(params)
    @departure = params[:departure]
    @arrival = params[:arrival]
  end

  def to_s
    "Trip (#{departure.try(:created_at) || "?"} --> #{arrival.try(:created_at) || "?"})"
  end

  def self.all
    result, _ = Event.order(:created_at).inject([[], nil]) do |(result, previous_event), event|
      kinds = [previous_event.try(:kind), event.kind]

      case kinds
      when [Event::Kind::Departure, Event::Kind::Arrival]
        result << Trip.new(departure: previous_event, arrival: event)
      when [Event::Kind::Departure, Event::Kind::Departure]
        result << Trip.new(departure: previous_event)
      when [Event::Kind::Arrival, Event::Kind::Arrival]
        result << Trip.new(arrival: event)
      end

      [result, event]
    end

    last_event = Event.order(:created_at).last
    if last_event.kind == Event::Kind::Departure
      result << Trip.new(departure: last_event)
    end

    result
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  module Kind
    Arrival = "arrival"
    Departure = "departure"
  end
end

app/models/trip.rb
class Trip
  attr_reader :departure, :arrival

  def initialize(params)
    @departure = params[:departure]
    @arrival = params[:arrival]
  end

  def date
    departure.try(:timestamp).try(:to_date) || arrival.try(:timestamp).try(:to_date)
  end

  def departure_time
    departure.timestamp.to_s(:time) if departure
  end

  def arrival_time
    arrival.timestamp.to_s(:time) if arrival
  end

  def duration
    return nil unless departure && arrival

    arrival.timestamp - departure.timestamp
  end

  def duration_string
    Time.at(duration).utc.strftime("%H:%M:%S") if duration
  end

  def to_s
    "Trip (#{departure.try(:timestamp) || "?"} --> #{arrival.try(:timestamp) || "?"})"
  end

  def self.all
    result, _ = Event.order(:timestamp).inject([[], nil]) do |(result, previous_event), event|
      kinds = [previous_event.try(:kind), event.kind]

      case kinds
      when [Event::Kind::Departure, Event::Kind::Arrival]
        result << Trip.new(departure: previous_event, arrival: event)
      when [Event::Kind::Departure, Event::Kind::Departure]
        result << Trip.new(departure: previous_event)
      when [Event::Kind::Arrival, Event::Kind::Arrival]
        result << Trip.new(arrival: event)
      end

      [result, event]
    end

    last_event = Event.order(:timestamp).last
    if last_event.try(:kind) == Event::Kind::Departure
      result << Trip.new(departure: last_event)
    end

    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order("timestamp DESC")
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def add_arrival
    Event.create(kind: Event::Kind::Arrival, timestamp: Time.zone.now)
    redirect_to root_url
  end

  def add_departure
    Event.create(kind: Event::Kind::Departure, timestamp: Time.zone.now)
    redirect_to root_url
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def delete_all
    Event.all.delete_all
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:kind, :timestamp)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @trips = Trip.all.reverse
  end

  def csv
    require 'csv'

    trips = Trip.all

    send_data(
      CSV.generate do |csv|
        csv << [
          "date",
          "departure time",
          "arrival time",
          "duration",
        ]

        trips.each do |trip|
          csv << [
            trip.date,
            trip.departure_time,
            trip.arrival_time,
            trip.duration,
          ]
        end
      end
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>

  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.datetime_select :timestamp %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Kind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.timestamp.to_s(:long) %></td>
        <td><%= event.kind %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Event', new_event_path %></p>
<p><%= link_to 'Home', root_path %></p>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @event.kind %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<form action="/add_departure"><input type="submit" value="Log Departure" style="width: 100%"></form>
<br />
<form action="/add_arrival"><input type="submit" value="Log Arrival" style="width: 100%"></form>
<br />

<table>
  <tr>
    <th>Date</th>
    <th>Departure Time</th>
    <th>Arrival Time</th>
    <th>Duration</th>
  </tr>

  <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.date %></td>
      <td><%= trip.departure_time %></td>
      <td><%= trip.arrival_time %></td>
      <td><%= trip.duration_string %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Download', data_csv_path %></p>
<p><%= link_to 'Edit raw events', events_path %></p>
<p><%= link_to 'Clear all', delete_all_path, data: { confirm: 'Are you sure?' } %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ezlogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style type="text/css">
td, th {
  padding: 5px;
}
  </style>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>